### ISSUE TITLE
Pod file not up to date?

### ISSUE THREAD

**Issue by foffux** [liweihan/LIGRippleView#1]
Hello
I have just installed your pod. But version I installed trough cocoa pods is different from the one I can see if I clone the repo. Clone repo is up to date whereas cocoa pods does not. Please, can you update your pod file so that when I run pod install I can get latest version (the one with new custom parameters)?
Thank you.

**Comment by liweihan** [comment]
Thanks for reminding, should be up to date now.

**Comment by foffux** [comment]
Hello
Thanks for the quick fix. Now it is up to date.
You can close this issue.
