### ISSUE TITLE
Help using this pod

### ISSUE THREAD

**Issue by foffux** [liweihan/LIGRippleView#2]
Hello.
I am using your pod but I have a question. I would like to trigger first star animation method and when it is finished, run automatically finish animation method. I would not trigger animation though a button.
How can I do it?
I can see in your pod :

``` javascript
#pragma mark - animation delegate methods
- (void)animationDidStop:(CAAnimation *)anim finished:(BOOL)finished
```

But it is not used in main file and there is not a delegate protocol usable.
Can you explain me and help with this issue?
Thank you.

**Comment by foffux** [comment]
Any news?
Thank you.

**Comment by liweihan** [comment]
Hi there, If you want to trigger the whole animation, just call both start/stop 
[rippleView startAnimation];
[rippleView stopAnimation];

**Comment by foffux** [comment]
Hello
Thanks for your help, it works great.
We can close it.
Bye.
